### ISSUE TITLE
Need help exporting the game to GameMaker project

### ISSUE THREAD

**Issue by Electricstar** [krzys-h/UndertaleModTool#101]
I'm having trouble exporting the game into a GameMaker project. All that happens is that I get a dog screen when selecting the option.

I'm pointing the game to Gamemaker.exe, and I don't see any "GMDebug.exe". I don't know what to do with "GraphViz" either. Help??

**Comment by colinator27** [comment]
The "export to gamemaker project" option is kind of a joke, for now at least. Due to potential legal complications with it, nobody really wants to add that functionality.

By the way, GraphViz is simply used for visualization of bytecode branching in the code viewer. GMDebug is probably the GameMaker debugger, and that's used to... debug...

**Comment by krzys-h** [comment]
Yeah, I basically added that easter egg because people have been asking for this option and while it may be possible I don't really want to implement it for legal reasons. That would most likely lead to people reusing parts of Toby's code in unrelated fan games and that just feels wrong compared to just slightly modding the game itself.

The GMDebug stuff works with GMS1.4 only, it won't work on GMS2 games. GraphViz is used for visualizing the assembly blocks, which is mostly just used to debug the decompiler, you don't really need that.
