### ISSUE TITLE
Segmentation Fault when decompiling

### ISSUE THREAD

**Issue by Archie-osu** [krzys-h/UndertaleModTool#1037]
### Describe the bug

When opening HoloCure's ``initItems`` GlobalScript, UMT hard-crashes with an access violation.
Even if Visual Studio is attached and UMT is built in Debug mode (as seen on the video below), no exception is ever caught?

The same crash happens when downloading the current Bleeding Edge build; no output is ever produced.

The code entry disassembles fine, no crashes there.

Video link is [here](https://streamable.com/fmmfii)

### Reproducing steps

1. Open [HoloCure](https://kay-yu.itch.io/holocure)
2. Try to decompile ``gml_GlobalScript_initItems``

### Setup Details

UMT version: bleeding edge 85430c5, also the one from #1036
OS: Windows 10 - 21H2 (19044.1766)
GM version: Unknown precisely, at least 2022.3 - ``Data.GM2022_3`` is ``True``

**Comment by steviegt6** [comment]
Some elaboration after testing and debugging from Archie and me:

- The actual crash is from a stack overflow, which can be seen if you use `dotnet` as the host instead of the `.exe` app host (otherwise console messages don't print).
- With temporary mitigation in place, you can observe a mostly-decompiled file [here](https://github.com/krzys-h/UndertaleModTool/files/9038588/initItems_V.gml.txt).
   - Search for `Unable to deduce name - stack overrun` to see where it begins to infinitely recurse.

Mostly everything past the initial SO discovery was done by Archie, I'll try to notice any bytecode patterns and whatnot after getting some shut-eye.
