### ISSUE TITLE
"Double Arrays" in scr_monstersetup

### ISSUE THREAD

**Issue by warestarstuff** [krzys-h/UndertaleModTool#110]
(forgot to mention this is for deltarune! oops)

I'm not sure if this appears anywhere else, but for some odd reason the decompiled code in scr_monstersetup will create "double arrays" 

As for example:
```
00083: pushi.e 1
00084: pushi.e -5
00085: push.v self.myself
00087: conv.v.i
00088: break.e -1
00089: push.i 32000
00091: mul.i.i
00092: pushi.e 0
00093: break.e -1
00094: add.i.i
00095: pop.v.i [array]canact
```

This SHOULD apparently read something like this in the decompiled code: `global.canact[(self.myself * 32000) + 0] = 1`

But instead it appears like this: `global.canact[self.myself][0] = 1`

**Comment by Myriachan** [comment]
This is for Deltarune.

**Comment by colinator27** [comment]
That's intentional, it signifies a 2-dimensional array. Technically if it were GML-compatible, it would read `global.canact[self.myself, 0] = 1`, though that's less conventional.

To answer the question about `break.e -1`, I believe it's for debugger purposes to check if it accidentally has a bad array index (and if it does, the runner will show a fatal error probably). The `-5` is pushed to the stack beforehand so that it knows the `[array]canact` is `global`, because -5 is the "type id" for `global`.

**Comment by colinator27** [comment]
Back to the original issue at hand, the multiplication by 32000 and addition is compiler-generated, and technically not what the source looked like.

**Comment by Myriachan** [comment]
I get the feeling that Game Maker is not written very well.  Thank you.

**Comment by colinator27** [comment]
Yeah, honestly that could have been implemented much better.

**Comment by krzys-h** [comment]
@colinator27 ugh, I should really start researching what the actual GML syntax is instead of assuming it's something sane like in other programming languages :P

@Myriachan yeah, your feeling that Game Maker is not really well written is quite correct, but I guess it's because of tons of compatibility code for older versions (the GMS2 runner can run GMS1.4 games just fine and I feel like that compatibility goes a lot deeper than that)

Like, here is the 1.08 undertale on GMS2 runner which is using a data file before some large room format changes with Layers and stuff, works absolutely fine:
![image](https://user-images.githubusercontent.com/1517255/49333255-9efefa80-f5bb-11e8-8030-cf018c1a98f6.png)
