### ISSUE TITLE
Custom sprites will not "translate" into a number when entering it into the disassembler

### ISSUE THREAD

**Issue by warestarstuff** [krzys-h/UndertaleModTool#113]
Sorry if the title is a bit confusing, but in body text I feel like it is a bit simpler to grasp.

I try to enter in the disassembler the name of a custom sprite I added a while ago...

![image](https://user-images.githubusercontent.com/36561313/49415374-7a825a00-f744-11e8-9a1d-bda80441a77b.png)

But when I'm finished, and I check it out in the decompiler, it changes the number to '0'

![image](https://user-images.githubusercontent.com/36561313/49415407-9685fb80-f744-11e8-8a6d-6fd32f543034.png)

This is the same for the disassembly- it displays 0

(And if anyone asks- yes, I am spelling the name of the sprite correctly.)

edit: this is for deltarune

edit 2: I don't actually think this is too consistent. The script I am currently making works completely fine, there isn't an issue with this supposed bug. But it seems on other scripts it just won't work? I'll try to find a way to replicate it

edit 3: it seems to happen with "create" scripts. you can test this out on objects like obj_rudinnranger and possibly others.

edit 4: the bug is actually completely different from what i described. when you look in the decompiler, it obviously just says "0" but if you click on it...

![image](https://user-images.githubusercontent.com/36561313/49454877-19926a80-f7b4-11e8-901f-269cf7ab0e08.png)

and whats REALLY odd is that its the same sorta thing in the disassembly, it still displays "0" as the spriteid, despite it supposedly being the custom sprite

**Comment by Kneesnap** [comment]
This issue is because the sprite name was used in the assembly instead of the sprite id. It was not properly used.

**Comment by Grossley** [comment]
Sprite ID can be used in the assembly where it gets automatically converted into an ID. This does not seem like a valid reason to close this issue.

**Comment by colinator27** [comment]
I don't believe this is a bug. The assembler will take the resource name, convert it to an ID, and assemble that. The reason why you don't see the sprite name in the decompiled output is because there is literally know way for the decompiler to tell if that variable is a certain type of resource - at least, not with our current setup. It would require propagating through tons of code to find its usages, and that could take a lot of resources.

The only reason why `hurtsprite` there shows the sprite name is because it is a special case for Undertale/Deltarune. Though, maybe we should add more special cases in the future. However, we also do want to have support for custom type definitions for different games, in some external file that could be loaded.

**Comment by Kneesnap** [comment]
Yes. I'd like to clarify what happened.

I cannot reproduce this. It appears to me like for some reason the sprite you added has the id 0. This should never be the case, unless you somehow deleted the existing sprite 0 and made a new one. The reason it says zero is because either that sprite doesn't exist with that name, or the actual sprite id is zerl.

**Comment by Grossley** [comment]
> 
> 
> I don't believe this is a bug. The assembler will take the resource name, convert it to an ID, and assemble that. The reason why you don't see the sprite name in the decompiled output is because there is literally know way for the decompiler to tell if that variable is a certain type of resource - at least, not with our current setup. It would require propagating through tons of code to find its usages, and that could take a lot of resources.
> 
> The only reason why `hurtsprite` there shows the sprite name is because it is a special case for Undertale/Deltarune. Though, maybe we should add more special cases in the future. However, we also do want to have support for custom type definitions for different games, in some external file that could be loaded.

I believe you're misunderstanding what's happening here. I believe what the bug is that a non- ID 0 sprite is being represented as ID 0. The actual sprite appearing as a sprite would be nice but that's not the problem here as far as I can tell. 

I think that this issue should be closed until @warestarstuff provides more information as to what exactly the problem is, what steps were taken to trigger the problem, what UndertaleModTool version, basically way more information is needed so that there's a reliable way to reproduce the bug. Besides, it's more than likely that (if this issue ever existed) that it was fixed in 0.2.0+.

**Comment by colinator27** [comment]
I believe that they just inserted a sprite at index 0, otherwise the dropdown would never have shown that...

**Comment by Grossley** [comment]
> 
> 
> I believe that they just inserted a sprite at index 0, otherwise the dropdown would never have shown that...

That makes sense. That means that this issue should be closed. Unless it truly is inconsistent as they stated. But we don't really have enough information to even reproduce it so I would just keep it closed.
