### ISSUE TITLE
Replace specific segments

### ISSUE THREAD

**Issue by Kardch** [krzys-h/UndertaleModTool#116]
Every time I have to replace code from the game I have to use all the code to replace the original, sometimes is a pain in the ass because the code is too big and I have to add those double commas. Is there any other way to actually replace just some segments and not the entire code? Thanks in advance!

**Comment by colinator27** [comment]
Are you referring to the scripting API or the editor?

**Comment by krzys-h** [comment]
The API, probably. There are functions Replace and Add but nothing more.

I wanted go add something to add in the middle, but couldn't figure out a good way to do it (adresses may change after you install other mods and the API was designed with a bit of cross-mod compatibility in mind - hence all of the EnsureDefined instead of just adding things blindly). Your best bet right now is probably to disassemble and do replacements on the string (look at my Jevil mod, it has some hacks like this).

I would definitely like to add at least Prepend though.

**Comment by colinator27** [comment]
I am actually working on a mod and recently added a new (untracked) function to that section, and it's literally just `Insert` like inserting into a list. All you have to do is locate the patch index of where you want to go, using a function like this:
```cs
int GetPatchIndexVarPop(string variableName, UndertaleCode code)
{
    for (int i = 0; i < code.Instructions.Count; i++)
    {
        if (code.Instructions[i].Kind == UndertaleInstruction.Opcode.Pop && code.Instructions[i].Destination.Target.Name.Content == variableName)
        {
            return i + 1;
        }
    }
    throw new Exception("Failed to find patch index");
}

```

**Comment by colinator27** [comment]
Oh, huh...

**Comment by Kardch** [comment]
Well just saw this https://github.com/krzys-h/UndertaleModTool/blob/3683fa68482ddc4d0857088c6e0d41941832a099/UndertaleModTool/SampleScripts/HeCanBeEverywhere.csx#L897-L904

I mean, this is good idea (but a bit hacky) for small replacements but when it comes to replacing more than 100 lines then well it stills better than nohing but well is kinda messy and I would really like to see that improved, just saying 😅

**Comment by Kneesnap** [comment]
This should no longer be relevant with the revamp plans.

**Comment by Kardch** [comment]
@Kneesnap Nice
