### ISSUE TITLE
Unable to change whole numbers into decimals

### ISSUE THREAD

**Issue by Electricstar** [krzys-h/UndertaleModTool#120]
![undertaleerror](https://user-images.githubusercontent.com/14850864/49701780-c1e26d80-fbbe-11e8-9d12-2f729a0f31d0.png)
Is there any reason this is happening? I'm currently in the process of trying to do a basic 60FPS mod for Undertale, and while I was trying to change Frisk's X and Y speed, which I think is 3, to 1.5, I get this exact error box. However, I can replace the 3 with a 2 just fine. The error seems to happen when trying to change whole numbers into decimals. However the game lets me change numbers that are already decimals just fine when adding more zeroes or even turning them into whole numbers (I.E: Replacing 0.5 with 1). It's just turning whole numbers into decimals that gives me this error box.

**Comment by krzys-h** [comment]
The instruction on the left also specifies the type, which is usually a 16-bit integer. Since it can't parse your input as an integer, it falls back to trying to parse it as an object name... and crashes, because I forgot to put in an error message apparently :P

To use a floating point number instead, you will have to change the `pushi.e` (push 16-bit immediate of type 'e' which is 16-bit int) instruction to `push.d` (push immediate of other types with type 'd' which is a double) and possibly update types in all instructions that use the pushed value.

Yeah... assembly edits are hard

**Comment by Electricstar** [comment]
Yeaaaah... I don't think i'm cut out for this then. The only things i've done with this mod so far is (try to) make the intro run at 60FPS with little success outside getting fade-in and fade-out speed right, save point animation and Frisk's animations and movement. This kind of mod would drive me insane without a GameMaker project, and while i'm aware of the issues that'd bring, i'm still hoping it could be done so mod creation could be easier... well, for me at least.

**Comment by colinator27** [comment]
I think the plan is that eventually editing the code in the high-level version will be possible. I'm nearly done writing the GML compiler for it (I recently tested it in a test script and it works!), and all that's left after that is ensuring the output is fully GML-compatible.

By that point it should be very easy to make changes like this. That can probably be tracked on #43 though.

However, maybe this issue could be a call to make the error messages more friendly for things like this, which I think I remember seeing in the code somewhere as a comment...
