### ISSUE TITLE
Add support for GMS2 sprites in room editor

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#130]
GMS2 added a way to add sprites directly to rooms, which we don't support yet in the editor. While I don't think Deltarune uses that, it would be a nice addition for other games and possibly mods.

**Comment by crashindoll** [comment]
Deltarune uses this feature to add sprite instances (or "graphics" as the variable names suggest) into rooms to be used for the different languages along with the lang_helper object.

Is it possible this could be implemented soon? Without this feature (or the export script, which is probably not going to be published soon due to legal reasons) it is not yet possible to translate Deltarune completely including all textures/sprites.

**Comment by Grossley** [comment]
Is this resolved?
