### ISSUE TITLE
Error opening a data.win file (Portuguese version)

### ISSUE THREAD

**Issue by fahem1999** [krzys-h/UndertaleModTool#141]
Recently, I have downloaded an unofficial Portuguese translation of Deltarune. But when I open the file, I am greeted with this error everytime. It didn't occur when I opened the original (English/Japanese).

Is there a way to fix this?
https://i.imgur.com/q2Li7LDr.jpg

Here's the download link of the data.win:
https://mega.nz/#!Xg1inAqS!Z9mekMRaSG1XpKJIUoe7nbecPH3v21Owxzt_RQq_x0Y

**Comment by krzys-h** [comment]
My guess is that whatever was used to edit it corrupted the file in such a way that the game can still read it, but it's not entirely correct. This is a known problem that happened with some older tools. I'll double-check what exactly happened later.

**Comment by fahem1999** [comment]
Alright, thought it was some error from my side, thanks for explaining.

**Comment by Mc-muffin** [comment]
This is weird, in the data.win at 0x006FE788 there is nothing (i.e just zeroed data) which is weird as that is the first pointer in the TXTR chunk. Changing the pointer to an existing one just throws an I/O error and adding a png to that location also gives out an I/O error but at a different location. It seems that is just the TXTR chunk that is malformed.

**Comment by krzys-h** [comment]
Oh, I didn't even notice this was about Deltarune at first, I'm 99% sure it was made with UndertaleModTool then since I'm not aware of any other tool that supports GMS2.

@Mc-muffin umm, is it actually? The first pointers seem to be 0x005B0480, 0x0065DF00, 0x00743B00. The problem must be with one of the PNGs, because data.win does not actually store file length anywhere so the reading code must actually parse the PNG file to determine the length.

**Comment by Mc-muffin** [comment]
You are right, my bad. (Don't even know now where I got that from ._.) I'm with you that the problem must be one the PNGs.

**Comment by krzys-h** [comment]
I just improved the object reading a bit to better handle cases like this - should be released with a new version soon
