### ISSUE TITLE
Do not replace pieces of scripts with errors

### ISSUE THREAD

**Issue by name86546745275426546** [krzys-h/UndertaleModTool#1459]
### Which component should be improved?

Decompiler

### Describe your feature suggestion in more detail

Hi, im trying to edit a script that the decompiler does not understand. When i enter the script, the decompiler just deletes functions and scripts, and that is making my game crash. Just show the error in a pop up window and just do not show the pieces of text that cant be decompiled.

**Comment by Jacky720** [comment]
The decompiler alone will not actually break anything. That only happens if you re-compile the broken code, which would generally result in a blanked code entry. Try not doing that.

The suggestion is still valid (although such errors are harder to copy into GitHub or Discord than those displayed in the editor). This is just a workaround suggestion.

**Comment by name86546745275426546** [comment]
> The decompiler alone will not actually break anything. That only happens if you re-compile the broken code, which would generally result in a blanked code entry. Try not doing that.
> 
> The suggestion is still valid (although such errors are harder to copy into GitHub or Discord than those displayed in the editor). This is just a workaround suggestion.

 Did not know that, thanks
