### ISSUE TITLE
Clean up global variables in Decompiler.cs

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#190]
```csharp
public static Dictionary<string, AssetIDType[]> scriptArgs;
public static Dictionary<UndertaleVariable, AssetIDType> assetTypes;```

Reportedly, by the comments in the code, these cause memory leaks/are ugly. I'm not entirely sure what these are used for right now, but I'm pretty sure we need to refactor the code.

**Comment by Kneesnap** [comment]
Everything but scriptArgs should be taken care of in https://github.com/krzys-h/UndertaleModTool/commit/d5e1b85aa5d2a23a0822f8ea45b15d3c891961b0

scriptArgs I haven't done yet, and I'm slightly hesitant because we'd make the time complexity of decompilation much worse if we made this something that got reset for each script / decompile, because it would mean decompiling all the blocks extra times.

**Comment by Kneesnap** [comment]
So, after discussion, we initially decided to keep scriptArgs global, since it would cause some slowdown if we did not.

However, upon further consideration, I recalled that scriptArgs is ThreadStatic. Which means there are multiple of this anyways. So, instead, I'm going to move this into DecompileContext, and allow for manual resetting, ie it will not reset each decompile.

**Comment by Kneesnap** [comment]
Done. https://github.com/krzys-h/UndertaleModTool/commit/2e19b823b3bd0688f0d82e36651fcc81d6d57a66
