### ISSUE TITLE
[Help Wanted] Couldn't add unimported builtin functions.

### ISSUE THREAD

**Issue by TML233** [krzys-h/UndertaleModTool#239]
I followed the developer's instructions in #155 
I right-clicked the "Function" in the resources tree, and selected the "Add" button.
Then I changed the name of the function to "asset_get_index".
But when i called this function, it always returns 0.
I'm pretty sure that "asset_get_index" is a builtin function in GMS1.
Please help, thanks a lot!!

**Comment by Grossley** [comment]
I do not see why you are adding that function in that way if it is already a builtin. Seems like you could just edit the decompiled code and add your uses of "asset_get_index" there.

**Comment by TML233** [comment]
> I do not see why you are adding that function in that way if it is already a builtin. Seems like you could just edit the decompiled code and add your uses of "asset_get_index" there.

No, Toby didn't use that function in the original Undertale. When I call "asset_get_index", the editor prompted me "Function not found".

**Comment by Grossley** [comment]
This might be an issue with disassembly editing but decompiled code editing does not require any of these issues. I just tried decompiled code editing and used it was able to add and use builtin functions just fine. And I'm sure that the disassembly code can be made to work if you really want to but I don't really see the point when you have the option of decompiled code editing. 

This issue is not reproducible and should be closed.

**Comment by TML233** [comment]
How did you try to reproduce the issue? I'm 100% sure It's not the case i met.

**Comment by TML233** [comment]
And what did you mean "you tried decompiled code editing"? The decompiled GML is not editable, only the byte codes are editable.

**Comment by Grossley** [comment]
The decompiled code is editable in release 0.3.0.

**Comment by TML233** [comment]
oh crap thats cool, I used 0.2.0 and edited the gml asm at that time. Things maybe fixed in the new version. I would try that later.
