### ISSUE TITLE
Sorry for the constant questions, but how exactly do you use the room editor?

### ISSUE THREAD

**Issue by Caylie-C** [krzys-h/UndertaleModTool#24]
I mean, I can retexture and move stuff around, but how do you add/remove objects in a single room?
(Sorry for the constant questons, just REALLY eager to use this on Undertale)

**Comment by krzys-h** [comment]
For removing, make sure the room object list is selected (that is a small bug) and click Delete on the keyboard.
For adding objects, either drag and drop a GameObject from a main tree on the left onto the room preview or just ctrl+c/ctrl+v existing ones
For adding tiles, ctrl+c/ctrl+v existing ones, there is no other add support yet. You can edit them afterwards if needed.
Backgrounds/Views are not supposed to be added or removed, there is always exactly 8 and you just enable or disable them as needed.

If you want to do anything meaningful like adding new interactable objects with dialogs or changing door destinations (*) you will need to write new scripts for them, and that is not easy as it has to be done at assembly level (but at least it's technically possible now!)

(*) but you can use the fact that doorA is always +1 room, doorB is -1 room, doorC is +2 and doorD is -2. The only problem is, you can't really insert a room in the middle of the list because then all the scripts in the game would break so I didn't even make that an option.
