### ISSUE TITLE
[MixMod] Crash

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#35]
https://www.reddit.com/r/UnderModders/comments/9kb2lh/mod_its_undertale_but_every_time_a_song_plays_its/e8sx9be/

**Comment by Grossley** [comment]
I am copying the contents of that Reddit comment here for the sake of redundancy if it gets deleted: 

> Game Crashed as soon i hit Space (Opening Sequence Steam 1.08) Trying again
> 
> Deleted Steamapi.dll
> 
> Trying with Firefox as Default Broswer (Was Chrome)
> 
> Here is the error
> 
> ___________________________________________
> 
> ############################################################################################
> 
> FATAL ERROR in
> 
> action number 1
> 
> of Key Press Event for <Space> Key
> 
> for object obj_time:
> 
> 
> 
> ds_list_size argument 1 incorrect type (undefined) expecting a Number (YYGI32)
> 
> at gml_Script_youtube_load_song
> 
> ############################################################################################
> 
> --------------------------------------------------------------------------------------------
> 
> stack frame is
> 
> gml_Script_youtube_load_song (line 0)
> 
> gml_Object_obj_time_KeyPress_32
 
Can this be reproduced? The script in question is the "MixMod" script. The game apparently crashes as soon as Space is entered on the Opening Sequence on Undertale version 1.08.

I read on #131 that it was fixed by just restarting the game. However, I am unsure as to whether that is the actual solution or merely a bandaid/coincidental fix to a more fundamental problem. Therefore I would like this to be reproduced if possible.

**Comment by Grossley** [comment]
Can this be reproduced? The script in question is the "MixMod" script. The game apparently crashes as soon as Space is entered on the Opening Sequence on Undertale version 1.08.

I read on #131 that it was fixed by just restarting the game. However, I am unsure as to whether that is the actual solution or merely a bandaid/coincidental fix to a more fundamental problem. Therefore I would like this to be reproduced if possible.

**Comment by Kneesnap** [comment]
@Grossley Do you mind attempting to reproduce this bug on both 1.08 and other versions?

**Comment by Grossley** [comment]
@Kneesnap Sure, I can try it eventually.

**Comment by Kneesnap** [comment]
Fixed! For future reference, make sure to follow the guide at https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModTool/SampleScripts/MixMod_README.md

This should be functional on the dev branch again.
