### ISSUE TITLE
Feature request: CLI tool

### ISSUE THREAD

**Issue by PoroCYon** [krzys-h/UndertaleModTool#5]
Because not everyone can use WPF (Mono users running Linux exist, too!), could you please add a CLI simple version of the tool, so I can try it out?

Thanks

**Comment by krzys-h** [comment]
That is on my TODO list as I am mostly a Linux user myself! I just wanted to try something different this time. UndertaleModLib is cross-platform (or at least is supposed to be as I didn't verify that yet)

One huge benefit you lose by using CLI and text files is the ability to follow references by double-clicking on them - and that is something that you do A LOT with this tool. So much that I had to add a back button because you sometimes go 3-4 levels deep or even more (room->object->code->sprite referenced in code->tpag->texture).

For now, you can do what I was doing early in development - browse the data with code or a debugger. It takes literally one line of code to load the data file.
```csharp
UndertaleData Data = UndertaleIO.Read(new FileStream(@"data.win", FileMode.Open));

foreach(var code in Data.Code)
{
    Console.WriteLine(code.Name.Content);
    Console.WriteLine(Decompiler.Decompile(code));
}

Console.WriteLine(Data.Objects.ByName("obj_time").EventHandlerFor(EventType.Create).Name);

Data.Objects.ByName("obj_time").Name = Data.Strings.MakeString("obj_this_is_not_time");

UndertaleIO.Write(new FileStream(@"newdata.win", FileMode.Create), Data);
```
You should be also able to run scripts this way as they are just C# code (or C# scripts actually, which is just C# with a bit relaxed syntax), just remove the calls to ScriptMessage and EnsureDataLoaded.

I was also able to get the tool running under wine with `WINEARCH=win32 WINEPREFIX="/some-wineprefix-path" winetricks -q dotnet461` ` WINEARCH=win32 WINEPREFIX="/some-wineprefix-path" wine UndertaleModTool.exe` (note the -q parameter to winetricks - apparently dotnet461 installer UI crashes so you have to run it in quiet mode)
![image](https://user-images.githubusercontent.com/1517255/45617403-88440f80-ba72-11e8-9b13-b8ededa8ce89.png)

**Comment by Kneesnap** [comment]
This will be rendered obsolete by the UI overhaul plans: https://github.com/krzys-h/UndertaleModTool/issues/182
