### ISSUE TITLE
4K on UMT

### ISSUE THREAD

**Issue by SlayerIbn** [krzys-h/UndertaleModTool#687]
There's problems to import graphics having a 4K display screen.

**Comment by SolventMercury** [comment]
Hello!
Your issue lacks clarity - in order to give the development team the necessary tools to fix your problem, please provide:

1.) A detailed description of the error you are experiencing, and any effects it causes for you

2.) The expected normal behavior

3.) A set of steps to follow to recreate the error

4.) Pictures showing the error and error message

**Comment by Dobby233Liu** [comment]
I think this is a DPI issue

**Comment by Dobby233Liu** [comment]
I think this is caused by a non-100% DPI

**Comment by Grossley** [comment]
ImportGraphics should have an explicit DPI handler, if it doesn't, this is a grave oversight (called "DPI FIX").
