### ISSUE TITLE
this isnt an issue just got a question

### ISSUE THREAD

**Issue by Ringi0911** [krzys-h/UndertaleModTool#712]
how the actual f*ck do you use the decompiler? i like making mods for games with the actual source code, not just a tool that helps me see stuff.

**Comment by NyakoFox** [comment]
if you're thinking this decompiles a game into a gamemaker project, then you're wrong; that's a legality issue therefore is not supported. you're supposed to modify the game using the tool itself.

**Comment by Jacky720** [comment]
UndertaleModTool only has a fully-functional GML compiler (I assume you mean that, rather than the decompiler, which is very stable. There are scripts to export code as .gml files) for games older than Game Maker 2.3. There are some recent changes on the master branch to increase stability, but nothing is guaranteed as of yet. The best workaround is probably to compile the code in a dummy project in GameMaker and copy the resulting assembly over with UMT, or just to learn how that assembly works.
