### ISSUE TITLE
japaneese additional space space

### ISSUE THREAD

**Issue by NotedChord** [krzys-h/UndertaleModTool#77]

**Comment by NotedChord** [comment]
Okay
![image](https://user-images.githubusercontent.com/44927303/48602357-b1aaea00-e994-11e8-895e-008f5ac528ba.png)
i added my glyphs and replaced japaneese
and this happend

**Comment by NotedChord** [comment]
how can i delete additional space between japaneese letters?

**Comment by krzys-h** [comment]
Japanese font have some strange spacing changes scattered across the scripts, so probably no, not easily

**Comment by krzys-h** [comment]
They did not replace japanese characters, they added new ones. To the english font. Issue #8 should have more info.

**Comment by NotedChord** [comment]
> They did not replace japanese characters, they added new ones. To the english font. Issue #8 should have more info.

![image](https://user-images.githubusercontent.com/44927303/48659720-3cfcac00-ea77-11e8-8849-a73fdb6595ad.png)

**Comment by krzys-h** [comment]
Oh, I forgot the English fonts have Japanese characters too :P
Theat's mentioning onle removing them from the texture to make space, not the font definition. Make sure you put values appropariate for your font there. I can't yell you much more because I've never actually done this myself so I'm not sure what each of the values mean exactly.

**Comment by LinXP** [comment]
@NotedChord Oh, this is a very difficult technique. You need to lay out the pentagram from the irons, take a timbrel, sit down in the center and sing the song “Few halves” in Uzbek...
