### ISSUE TITLE
How do i add custom characters to the game? (I.E playable characters, NPCs etc.)

### ISSUE THREAD

**Issue by flufferi** [krzys-h/UndertaleModTool#779]
i am a complete noob at coding so excuse my lack of competence in this, but i do wanna try making a mod of a character of mine, but rather than replacing someone its adding someone in entirely. (Literally i think no one has covered if this is possible or a tutorial for it, but just asking here to see if it is possible.)

**Comment by Jacky720** [comment]
It's possible. The how is basically a test of your skills in every aspect of the tool: Adding objects to rooms, adding code to objects, knowing where to add code and which objects to add it to, importing sprites, attaching them to the code and/or the object, if you want to make something entirely new instead of another NPC you need to make a new object... The most I can really say without taking an hour to write it is, for the NPC part anyway, "add the sprite to obj_npc_room_Create_0, the dialogue to obj_npc_room_Alarm_0, and an obj_npc_room to the room you want the NPC in. And keep looking at the way the existing game does it. It's a mining tool as well as a modding one."

**Comment by Grossley** [comment]
Closed as out of scope.
