### ISSUE TITLE
Errors regarding sprite resizing

### ISSUE THREAD

**Issue by TheGamingManiac** [krzys-h/UndertaleModTool#78]
Earlier today, I attempted to change where a sprite reads whatever off of a sprite sheet, including resizing it. However, it gave me an error once I started to repack it. Thankfully, it finished, but the sprite was still scaled down in the game. I took a break for a few hours, and tried to load the .win again. Once I tried to load it, I got greeted to this.
![image](https://user-images.githubusercontent.com/26528643/48655550-fd35b600-e9dd-11e8-8add-158017f512da.png)
Any help? Thanks. Great tool, by the way. Makes Undertale modding actually bearable now.

**Comment by krzys-h** [comment]
I guess you changed the size of the sprite but didn't update the collision mask. You will need to do it since the game uses the sprite size to determine how many bytes of the mask to load - just export it, then resize it in a graphics program, change size in the tool and reimport when it shows the 'Invalid mask' error. The tool probably didn't finish writing and left you with a corrupted file that ends after the first write error, if the game managed to load that I would be quite suprised.

If that's not it, try to reproduce the write error you got since that's probably more significant.

**Comment by TheGamingManiac** [comment]
I've tried adding a mask that would work with the sprite I'm adding. Whenever I try to import it, I get this message.
![image](https://user-images.githubusercontent.com/26528643/48678581-d5b02c00-eb4a-11e8-8ed3-fd87a9e68b3a.png)

**Comment by krzys-h** [comment]
I heard that for some reason it's hard to get graphics programs to output 1BPP bitmaps... I'll consider adding an automatic conversion step

In the meantime you can try this: http://www.gimpusers.com/forums/gimp-user/18092-1-bit-monochrome-bmp

You may be also able to use imagemagick like so: `convert drawing.png -type bilevel -colors 256 drawing.bmp` (source: https://www.imagemagick.org/discourse-server/viewtopic.php?t=21421)

**Comment by TheGamingManiac** [comment]
Sorry for the late response, but it seems that the gimp method didn't work, and I cant really use imagemagick. Are there any other knows ways to convert it?

**Comment by TheGamingManiac** [comment]
Okay, it seems I almost have it working now, but now it's telling me that the sprite size is incorrect,
![image](https://user-images.githubusercontent.com/26528643/48679859-b6b99600-eb5a-11e8-9210-8e01ab139eda.png)

**Comment by TheGamingManiac** [comment]
Ah, I have it working now.
Thanks!
