### ISSUE TITLE
Mac/Linux builds of UndertaleModCLI

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#780]
It is my understanding that the main thing preventing cross-platform compatibility for UndertaleModTool is the WPF dependencies. This can be avoided with the UndertaleModCLI as it does not use WPF.

**Comment by Miepee** [comment]
In order to not clutter the release page with a bunch of different assets for UTMTCLI, it's possible to compile that project OS-independently, but dependent of .NET Core. May be a consideration for future releases.
<https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent>

**Comment by Miepee** [comment]
Was discussed in the discord server: having each OS as a separate build was preferred.

**Comment by Jacky720** [comment]
Soo, as an issue, this is resolved, right? We have cross-platform CLI.
