### ISSUE TITLE
Tab issues

### ISSUE THREAD

**Issue by Miepee** [krzys-h/UndertaleModTool#827]
- [x] back button / history is not working properly (proposed solution: Add opened tab to the history (probably, `Stack`) on tab switching, and remove closed tab from it. (Addressed on #831)
- [x] tab scroll bar should only be visible if its necessary, not always shown (Addressed on #831)
- [x] make prettier close icons.

**Comment by VladiStep** [comment]
+ _"tabs scroll bar sometimes overlaps data editor"_

**Comment by NyakoFox** [comment]
I said this in the discord server but I'll repeat it here

The way tabs are handled right now is, they're like shortcuts to editors. That means if you're in a tab, and you switch to another tab, the tab you just clicked on will load what it's supposed to show. Most programs with tabs don't do this because that's very slow and comes with a whole bunch of issues.

An example of an issue from this is, try writing code, not compiling, and switching to another tab. This use-case is very common, as referencing other tabs while you're writing code happens quite a lot, at least for me.

But since you switched tabs, it throws away whatever the tab you were just on was. Meaning that your changes were never compiled, and the code you just wrote was thrown away. And don't worry, next time you click on that tab, it'll decompile the code again!

This is a really bad method of handling tabs, and I know it won't be easy to change the behavior, but it _really_ needs to be done.

https://user-images.githubusercontent.com/87289390/162821612-e0e28457-452c-4b76-ba1e-eb918e4c55d3.mp4

**Comment by Jacky720** [comment]
- [ ] Tabs persist across data.win loads, appearing functional but referencing the wrong UndertaleData (which is not cleared from memory). Tabs should either close automatically on loading, or attempt to open the corresponding asset in the new Data.

**Comment by NyakoFox** [comment]
- [ ] Tabs should be able to be reordered, preferably with drag and drop.

**Comment by Miepee** [comment]
When a tab's title is too long, this happens:
![image](https://user-images.githubusercontent.com/38186597/166147014-8ec63073-db18-42be-9f7c-e554d7ff8bd1.png)

**Comment by NyakoFox** [comment]
Here's the ideal tab functionality that I suggested on the server:

- The list on the left will open things in a new tab, _**unless**_ you right click, and choose "**Open in current tab**".
- For everything _inside_ of a tab which would _open_ a new tab, for example, clicking on a code reference inside of an object's tab, it'll be opened in the current tab, **_unless_** you either middle click, or right click and choose "**Open in new tab**".

This is the most intuitive way to handle tabs. UTMT has an odd workflow, so you have to mix the behaviors of IDEs and web browsers to make it intuitive, and what I described is the best of both.

**Comment by Miepee** [comment]
-[ ] Make MMB on the items on the left open them in a new tab.

**Comment by Miepee** [comment]
- [ ] Back button history is currently handled a bit weird. If I try to operate everything in single-tab mode, then the back button will be greyed out for me all the time.

**Comment by Miepee** [comment]
Nyako's comment was the only thing left, which i sepereated into its own issue: #1537 
Thus, i'm closign this
