### ISSUE TITLE
Load error on YYC games (bytecode 17)

### ISSUE THREAD

**Issue by LinXP** [krzys-h/UndertaleModTool#89]
Load error (AUDO, bytecode17) 
http://i.prntscr.com/YaMO3fZpQsqFsrEfFReh9g.png
example games: Rivals_of_Aether_pc_bc17.win, Wandersong_Mac_bc17.ios, Crashlands_v1.4.7_Android_bc17.droid from [here](https://mega.nz/#F!HfxXwS5B!N_-Zfy_pgNp9KXLn3NO7RQ)

**Comment by krzys-h** [comment]
It appears these games use YYC. This means that actual game code is compiled into the game executable instead of the CODE block. CODE, FUNC and VARI used to be empty in this case for older bytecodes, but they seem to be entirely missing for bytecode 17.

Also, the error is not on AUDO, but on the post-loading phase. I will add another progress bar message to clarify that.

**Comment by krzys-h** [comment]
I opened #104 for implementing actual YYC support

**Comment by krzys-h** [comment]
Forgot to mention: all the games from your link seem to load now, not sure if everything about YYC games works fine though
