### ISSUE TITLE
Figure out the one weirdly encoded jump offset in Undertale

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#90]
I found exactly one weirdly encoded jump offset in Undertale and we still don't know what it means. It may occur in other games as well. See my original research documents an the JumpOffsetIsWeird variable, the code in question is ﻿in gml_Object_obj_battlebomb_Alarm_3.

ping @colinator27 @LinXP

**Comment by krzys-h** [comment]
#88 may be somehow related as it uses an int24 as well (or maybe not since we just figured out it's actually uint24)

**Comment by krzys-h** [comment]
@colinator27 came up with a wonderful example that illustrates the problem:
```gml
with (12)
{
	i = "stuff"
	i = "abc"
	i = "123"
	exit;
	i = 1;
}
```

```
00000: pushi.e 12
00001: pushenv 00019
00002: push.s "stuff"@3
00004: pop.v.s self.i
00006: push.s "abc"@5
00008: pop.v.s self.i
00010: push.s "123"@6
00012: pop.v.s self.i
00014: popenv -1048562
00015: exit.i
00016: pushi.e 1
00017: pop.v.i self.i
00019: popenv 00002
```

The weirdly encoded popenv is apparently supposed to mark an early exit from the popenv loop. We just need to know what the value actually is now.

**Comment by krzys-h** [comment]
And the raw offset value is... *drumroll* 0xF00000 (it's an int24)
So since the offset is encoded on the lowest 23 bits, I guess this was meant to be 0x800000 and somebody just flipped too many bits and nobody cared since the value is unused anyway

**Comment by colinator27** [comment]
Looking at the compiler, the code that writes the weird popenv instruction is this:
```
method_14(Enum12.const_39, eVM_Type.eVMT_Double, eVM_Type.eVMT_Error);
```
`Enum12.const_39` is 187 (0xBB), which is `popenv`, of course.

This is the same function to write double type instructions, and since Double is 0, and Error is 0xF, this kind of makes sense. So that was why I was thinking it would maybe be `popenv.d.e`... but that really means nothing.

So yeah this implementation seems perfectly fine as is. It's probably the easiest way to solve the problem without creating a mess.
