### ISSUE TITLE
Bug: the compiler removes return statements sometimes

### ISSUE THREAD

**Issue by cgytrus** [krzys-h/UndertaleModTool#900]
### Describe the bug

a return at the end of an if statement with other code in it removes the return when compiled

### Reproducing steps

1. Open a script (not sure if it works on the new functions thing, definitely works on legacy scripts)
2. Put the following code at the beginning:
```gml
if(some_var) {
    do_something()
    return;
}
```
3. Click away to compile the code
4. Observe the return disappear

### Setup Details

1. commit 61d0f89
2. win10 latest
3. Will You Snail?

**Comment by Jacky720** [comment]
This occurs because scripts automatically decompile with an unnecessary `return` at the end and I wanted to ignore that return to match bytecode. Thus, it can be fixed at [AssemblyWriter.cs#1019](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModLib/Compiler/AssemblyWriter.cs#L1019), but maintaining 1:1 compilation will require removing the unnecessary `return` generation. Not that that's a high priority.
