### ISSUE TITLE
Display proper GM version in the window title

### ISSUE THREAD

**Issue by Archie-osu** [krzys-h/UndertaleModTool#929]
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

Currently, even the latest DELTARUNE Chapter 2 builds show up as GMS 2.0.0.0 - I understand this is the version that UMT reads directly from the data.win, but given we can identify if a game uses 2022.x accurately, it should in my opinion be displayed instead.

Even if we can't identify all of the versions separately (as maybe the WAD format didn't change), the window title should include at least an approximation of what the version might be (think ``GM2022.3+``).

**Comment by Miepee** [comment]
Personally think that the approximate version should be shown in General Info (or in a another new tab?) rather than the title along with all the other extra stuff that currently isn't shown like `ShortCircuit` or `UseQoiFormat`.
Is there any reason why the GMS version and bytecode are shown in the title to begin with? Easier help for people posting screenshots I assume?

**Comment by Archie-osu** [comment]
In my opinion, the data.win version is less useful than the approximation - the approximation being in the window title would help with easily spotting which GM versions the tool's having issues with.

I like your idea of showing the hidden variables in a separate tab, and personally think the (now not-updated) data.win version should be moved there.

**Comment by Miepee** [comment]
> being in the window title would help with easily spotting which GM versions the tool's having issues with.

Well, if a game fails to load, then the window title won't even get a chance to update. If a game fails to save or other errors occur, then I don't think its that hard to ask for people to send what the variable is by looking at a certain tab. 
Alternatively, maybe put in a "copy troubleshoot information" button somewhere? Have seen some programs do that.

> personally think the (now not-updated) data.win version should be moved there.

The general info, options and language areas are all sorted by their respective chunks. Moving the version which is part of GEN8 out of the area that displays GEN8 info is not good UX.

I also think that this:
![image](https://user-images.githubusercontent.com/38186597/170456532-9e6532cd-0cbe-4b3c-bcc4-6cec2954aa8b.png)

Is much cleaner than this:
![image](https://user-images.githubusercontent.com/38186597/170456549-5c1e1c55-e6d7-48c7-8724-aca06fb1a02a.png)

**Comment by Archie-osu** [comment]
> The general info, options and language areas are all sorted by their respective chunks
Why is this even the case? The tool doesn't allow these values to be edited, and as far as I know no-one has ever actually used them.
To alter their values, you'd have to use the console, at which point you don't even need the UI and can just use UMTLib itself.

**Comment by Miepee** [comment]
The tool does allow all of the values to be edited.

**Comment by JohnnyonFlame** [comment]
> In my opinion, the data.win version is less useful than the approximation - the approximation being in the window title would help with easily spotting which GM versions the tool's having issues with.
> 
> I like your idea of showing the hidden variables in a separate tab, and personally think the (now not-updated) data.win version should be moved there.

My experience is that past GMS1.x that number only serves to confuse people. I have a script around that uses the fields in Data to tell the user what the approximate version is, and it's seeing a lot of use by the people testing titles on [the yoyoloader compatibility list](https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues), so I'm upvoting Archie here.

**Comment by Miepee** [comment]
When looking at the window title or the general info?
I'd personally would like to have the field in the general info as-is, but with some sort of notice to the user that YYG stopped updating that number past gms2 on a gms2+ data file.

**Comment by Archie-osu** [comment]
> with some sort of notice to the user that YYG stopped updating that number

This would be the worst UX imaginable. Someone could miss that notice, and then when asking for help be adamant their version is different from what it actually is.

**Comment by Jacky720** [comment]
> Someone could miss that notice, and then when asking for help be adamant their version is different from what it actually is.

Most users aren't looking at the general info tab to get their game's version. I assume the general info would have the warning and the window title would just have the more accurate version.

Relevant files for changing the title:
* [MainWindow.xaml#L15](https://github.com/krzys-h/UndertaleModTool/blob/befaae88d2a416b750ab10515e81405a9b3abee7/UndertaleModTool/MainWindow.xaml#L15): The actual title.
* [UndertaleGeneralInfo.cs#L468](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L468): The part of the title that makes everybody's favorite 2.0.0.0.
* [UndertaleData.cs](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModLib/UndertaleData.cs): Since the flags for versions past 2.0 are all stored in the UndertaleData rather than the GeneralInfo, we could add a ToString that returns the highest flag or GeneralInfo.

**Comment by Miepee** [comment]
> I assume the general info would have the warning

Yeah, meant this if it wasn't clear. Just have big red text under the 2.0.0.0 version box saying a warning for that.


> Since the flags for versions past 2.0 are all stored in the UndertaleData rather than the GeneralInfo

Why are they stored in UndertaleData to begin with? Wouldn't it be better to move them to GeneralInfo and make them an Enum, so that it isn't possible to do i.e. `GMS2022_1 = true; GMS2022_3 = true;`?

**Comment by Miepee** [comment]
Also sending as a separate message so it's easier to gather feedback via reactions:
Thoughts on just omitting the version + BC from the title bar all-together (akin to this)?
![image](https://user-images.githubusercontent.com/38186597/170498162-258cf8df-b8e6-4816-a55f-35aeac201b6f.png)

**Comment by Archie-osu** [comment]
> Also sending as a separate message so it's easier to gather feedback via reactions: Thoughts on just omitting the version + BC from the title bar all-together (akin to this)? IIRC the average user doesn't know what to do with that info anyway and for any help we need we can just tell users to send a screenshot from GeneralInfo if needed. ![image](https://user-images.githubusercontent.com/38186597/170498162-258cf8df-b8e6-4816-a55f-35aeac201b6f.png)

Omitting the version literally goes against the purpose of this issue. Not relevant.

**Comment by Jacky720** [comment]
> Why are they stored in UndertaleData to begin with? Wouldn't it be better to move them to GeneralInfo and make them an Enum, so that it isn't possible to do i.e. `GMS2022_1 = true; GMS2022_3 = true;`?

They're stored in the Data because GeneralInfo corresponds to an actual chunk, and the 2.2+ flags aren't stored in GeneralInfo. They're deduced from the way the file is parsed.

An Enum could work. Just as long as they're in the right order.
