### ISSUE TITLE
Some uses of globals add "self." incorrectly

### ISSUE THREAD

**Issue by Myriachan** [krzys-h/UndertaleModTool#96]
When uses of globals like `working_directory` or arguments like `argument0` are decompiled, the decompiler adds `self.` incorrectly.  This causes compiler errors if you attempt to recompile the decompiled script using Game Maker.

This is easily seen in Deltarune's gml_Script_scr_encountersetup `switch self.argument0`.  Similarly, scr_84_lang_load has a `working_directory` reference.

**Comment by colinator27** [comment]
Technically the type the GML compiler generates is `self`. However, it is unnecessary to export them to the high-level viewpoint of the code. In fact, I believe every single instance of `self.` could be removed from the decompiled code and it would be functionally equivalent. Though, it could be a little ambiguous. It's mainly a design decision.

The only way to solve this problem the way you suggest would be to have a whole list of the builtins (which I actually have because I'm rewriting the compiler for this project), because there's literally no assembly difference between normal instance variables and these kinds of builtins. That would kind of be a hassle though... so the most practical options are to either keep or remove `self.` from the output code, unless anyone else has any thoughts.

**Comment by krzys-h** [comment]
I thought that there is no problem in prefixing all variables with "self" since that's what the compiler actually generates and it worked fine for member variables when I checked. So I guess from what you are saying that you can't use self on a builtin variable? I guess we could remove them in that case, but leave them everywhere else for readability (yes, I know nobody writes it like that in GML :P). Builtins should be easy to detect by checking for `VarID == (int)InstanceType.Builtin` (value -6)

**Comment by krzys-h** [comment]
![image](https://user-images.githubusercontent.com/1517255/48952353-31f7bf00-ef42-11e8-817e-b239159a9e9d.png)
Yup, apparently you are right, fixing that right now

And about the build environment, it should work out of the box on Visual Studio 2017 if you tell it to pull the NuGet packages

**Comment by krzys-h** [comment]
Actually, this may be slightly more complicated than I thought because there are both "global built-ins" (argument0, room) and "instance built-ins" (x, y, id) and they both look the same in the data files. I guess I'll need to make another database hardcoded in the tool to resolve that...

**Comment by colinator27** [comment]
I have a list of those builtins already, at least 99% of them, including extremely obscure ones.

**Comment by krzys-h** [comment]
@colinator27 then I'll leave this for now, we'll deal with that once we have a list to work with

**Comment by colinator27** [comment]
I have this file that loads them into dictionaries, kind of weirdly because of the way I decided to do regex (it can probably be inlined or something), but here it is if it helps: https://gist.github.com/colinator27/58cd98e061164b34b63ce41e63fb1c32

**Comment by krzys-h** [comment]
Fixed in #162
