### ISSUE TITLE
make Exported embeded audio file names default to the name of the sound thay are attached to

### ISSUE THREAD

**Issue by MichaelHinrichs** [krzys-h/UndertaleModTool#98]
Or put import/export buttons in the sounds menu. Or display the name of the attached sound in the embedded audio menu, similer to how the embedded audio's number is displayed in the sounds menu.

I just don't want to need to count how far down in the sounds list any given sound is, then find the embedded audio file in the same place in it's own list, and hope I don't miscount the 10s of identicly named files, just to export 1 wav file with it's own name. EVERY. TIME.

look, I get it. gamemaker uses 2 different files for sound, but why cant ther data be displayed together on the menu?

**Comment by krzys-h** [comment]
This is not really feasible because the data structure is not a 1-to-1 relationship - you can have multiple sounds using the same file, and you can have files not attached to any sound name. You can also have sounds that don't have files attached to them. Since everything except the last one rarely happens in practice, I guess I could add something that looks through the sounds and assign the name based on that just for display purposes.

You also don't have to count the embedded audio items manually - just open the sound, and double click on the embedded audio element in the decription (or click the ... button on the right of it)
